use wm;
 -- PRODUTO CARTESIANO DA TABELA, TODAS AS LINHAS ESTÃO RELACIONADAS COM TODOAS AS COLUNAS
SELECT * FROM ESTADO E, CIDADE C;

SELECT * FROM ESTADO E, CIDADE C WHERE E.ID = C.ESTADO_ID;

SELECT e.nome as Estado, c.nome  as Cidade FROM ESTADO E, CIDADE C WHERE E.ID = C.ESTADO_ID;

SELECT 
	C.NOME AS CIDADE,
    E.NOME AS ESTADO,
    REGIAO AS REGIÃO
FROM ESTADO E 
INNER JOIN CIDADE C ON E.ID = C.ESTADO_ID;

--  
SELECT * FROM CIDADE C INNER JOIN PREFEITO P ON C.ID = P.CIDADE_ID;

SELECT * FROM CIDADE C LEFT JOIN PREFEITO P ON C.ID = P.CIDADE_ID;

SELECT * FROM CIDADE C RIGHT JOIN PREFEITO P ON C.ID = P.CIDADE_ID;


SELECT * FROM CIDADE C LEFT OUTER JOIN PREFEITO P ON C.ID = P.CIDADE_ID;

SELECT * FROM CIDADE C RIGHT OUTER JOIN PREFEITO P ON C.ID = P.CIDADE_ID;

SELECT * FROM CIDADE C LEFT JOIN PREFEITO P ON C.ID = P.CIDADE_ID
UNION ALL
SELECT * FROM CIDADE C RIGHT JOIN PREFEITO P ON C.ID = P.CIDADE_ID;

SELECT E.NOME, C.NOME  AS CIDADE
FROM EMPRESA E, EMPRESA_CIDADE EC, CIDADE C
WHERE E.ID = EC.EMPRESA_ID 
AND  C.ID = EC.CIDADE_ID
AND SEDE ;
