use wm;
-- CRIANDO TABELAS --

CREATE TABLE ESTADO(
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 nome VARCHAR(45) NOT NULL,
 sigla VARCHAR(2) NOT NULL,
 regiao ENUM('Norte', 'Nordeste', 'Centro-Oeste', 'Sul', 'Sudeste'),
 populacao DECIMAL(5,2) NOT NULL,
 PRIMARY KEY(id),
 UNIQUE KEY(nome),
 UNIQUE KEY(sigla)
);

CREATE TABLE PREFEITO(
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 nome VARCHAR(45) NOT NULL,
);

CREATE TABLE CIDADE(
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 nome VARCHAR(45) NOT NULL,
);

CREATE TABLE EMPRESA(
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 nome VARCHAR(45) NOT NULL,
);