use wm;

SELECT * FROM ESTADO;

SELECT NOME, SIGLA FROM ESTADO;

SELECT NOME AS "Nome do Estado", SIGLA FROM ESTADO;

SELECT NOME AS "Nome do Estado", SIGLA FROM ESTADO where regiao = "Sul";

SELECT NOME AS "Nome do Estado", SIGLA, POPULACAO FROM ESTADO
WHERE POPULACAO >= 10
ORDER BY POPULACAO;

-- DECRESCENTE

SELECT
	NOME AS "Nome do Estado", SIGLA, POPULACAO FROM ESTADO
WHERE POPULACAO >= 10
ORDER BY POPULACAO DESC;

